directory/urls.py
from django.urls import path

from directory.views import (
    CounterpartiesView,
    CounterpartyDeleteView,
    CounterpartyIdView,
    OrganizationsView,
    OrganizationIdView,
    OrganizationDeleteView,
    ProjectsView,
    ProjectsIdView,
    ProjectDeleteView,
    PaymentAccountsView,
    PaymentAccountIdView,
    PaymentAccountDeleteView,
    CurrenciesView,
    CurrenciesIdView,
    CurrencyDeleteView,
    RatesView,
    RatesIdView,
    RatesDeleteView,
    RatesParsingView,
    InitialDebtsView,
    InitialDebtIdView,
    InitialDebtDeleteView,
    ItemIdView,
    ItemsView,
    ItemDeleteView,
    ExpensesItemView,
    ExpensesItemIdView,
    IncomeItemView,
    IncomeItemIdView,
)

urlpatterns = [
    path("organizations/", OrganizationsView.as_view(), name="organizations"),
    path("organization/<int:pk>", OrganizationIdView.as_view(), name="organization_id"),
    path("organization/add/", OrganizationIdView.as_view(), name="organization_add"),
    path("<int:pk>/organization/delete/", OrganizationDeleteView.as_view(), name="organization_del"),
    path("projects/", ProjectsView.as_view(), name="projects"),
    path("project/<int:pk>/", ProjectsIdView.as_view(), name="project_id"),
    path("project/add/", ProjectsIdView.as_view(), name="project_add"),
    path("<int:pk>/project/delete/", ProjectDeleteView.as_view(), name="project_del"),
    path("payment_accounts/", PaymentAccountsView.as_view(), name="payment_accounts"),
    path("payment_account/<int:pk>/", PaymentAccountIdView.as_view(), name="payment_account_id"),
    path("payment_account/add/", PaymentAccountIdView.as_view(), name="payment_account_add"),
    path("<int:pk>/payment_account/delete/", PaymentAccountDeleteView.as_view(), name="payment_account_del"),
    path("counterparties/", CounterpartiesView.as_view(), name="counterparties"),
    path("counterparty/<int:pk>/", CounterpartyIdView.as_view(), name="counterparty_id"),
    path("counterparty/add/", CounterpartyIdView.as_view(), name="counterparty_add"),
    path("<int:pk>/counterparty/delete/", CounterpartyDeleteView.as_view(), name="counterparty_del"),
    path("initial_debts/", InitialDebtsView.as_view(), name="initial_debts"),
    path("initial_debt/<int:pk>/", InitialDebtIdView.as_view(), name="initial_debt_id"),
    path("initial_debt/add/", InitialDebtIdView.as_view(), name="initial_debt_add"),
    path("initial_debts/list", InitialDebtsView.htmx_list, name="initial_debts_list"),
    path("<int:pk>/initial_debt/delete/", InitialDebtDeleteView.as_view(), name="initial_debt_del"),
    path("currencies/", CurrenciesView.as_view(), name="currencies"),
    path("currency/<int:pk>/", CurrenciesIdView.as_view(), name="currency_id"),
    path("currency/add/", CurrenciesIdView.as_view(), name="currency_add"),
    path("<int:pk>/currency/delete/", CurrencyDeleteView.as_view(), name="currency_del"),
    path("rates/", RatesView.as_view(), name="rates"),
    path("rates/<int:pk>/", RatesIdView.as_view(), name="rate_id"),
    path("rates/add", RatesIdView.as_view(), name="rate_add"),
    path("rates/list", RatesView.htmx_list, name="rate_list"),
    path("rates/copy/<int:from_pk>", RatesIdView.as_view(), name="rate_copy"),
    path("rates/import", RatesParsingView.as_view(), name="rates_parsing"),
    path("<int:pk>/rates/delete", RatesDeleteView.as_view(), name="rate_del"),
    path("items/", ItemsView.as_view(), name="items"),
    path("item/<int:pk>", ItemIdView.as_view(), name="item_id"),
    path("item/add", ItemIdView.as_view(), name="item_add"),
    path("items/list", ItemsView.htmx_list, name="items_list"),
    path("<int:pk>/item/delete", ItemDeleteView.as_view(), name="item_del"),
    path("expenses_items/", ExpensesItemView.as_view(), name="expenses_items"),
    path("expenses_item/<int:pk>/", ExpensesItemIdView.as_view(), name="expenses_item_id"),
    path("expenses_item/add/", ExpensesItemIdView.as_view(), name="expenses_item_add"),
    path("income_items/", IncomeItemView.as_view(), name="income_items"),
    path("income_item/<int:pk>", IncomeItemIdView.as_view(), name="income_item_id"),
    path("income_item/add", IncomeItemIdView.as_view(), name="income_item_add"),
]

finance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("", include("directory.urls")),
    path("", include("payments.urls")),
    path("", include("planning.urls")),
    path("", include("registers.urls")),
    path("", include("users.urls")),
    path("", include("tools.urls")),
]

tools/urls.py
urlpatterns = [
    # path("s3cr3t/rel04d/", DataLoadView.as_view(), name="dataload"),
]

directory/models.py
from django.db import models
from django.contrib.auth.models import User
from directory.data import ITEMS
from directory.constants import (
    RECEIPTS,
    PAYMENTS,
    FINANCING,
    OPERATING,
    INVESTING,
    LOANS,
    PROJECTS,
    FIXED_ASSETS,
    OTHER,
    SALES_INCOME,
    DIRECT_EXPENSES,
    ADMIN_EXPENSES,
    COMMERCIAL_EXPENSES,
    PRODUCTION_COSTS,
)


class Organization(models.Model):
    """Basic information about the organization: name, general comments."""

    organization = models.CharField(max_length=100, unique=True)
    comments = models.CharField(max_length=250, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.organization

    class Meta:
        ordering = ["organization"]


class PaymentAccount(models.Model):
    """
    Basic information about the payment account of organization:
    bank, owner organization, currency of accounting, cash account type (yes|no), general comments.
    """

    account = models.CharField(max_length=50, unique=True)
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, blank=False, null=False)
    is_cash = models.BooleanField(blank=False)
    currency = models.ForeignKey("Currencies", on_delete=models.PROTECT, blank=False, null=False)
    comments = models.CharField(max_length=100, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.account

    class Meta:
        ordering = ["organization", "account"]
        verbose_name = "Payment account"
        verbose_name_plural = "Payment accounts"


class Project(models.Model):
    """Basic information about the project of organization: name, owner organization, general comments."""

    project = models.CharField(max_length=100, unique=True)
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, blank=False)
    comments = models.CharField(max_length=250, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.project

    class Meta:
        ordering = ["organization", "project"]
        verbose_name = "Project"
        verbose_name_plural = "Projects"


class Counterparties(models.Model):
    """
    Basic information about the counterparty:
    name, type (supplier, customer, employee, other), general comments.
    """

    counterparty = models.CharField(max_length=100, unique=True)
    comments = models.CharField(max_length=100, blank=True, null=True)
    suppliers = models.BooleanField(blank=True, default=False)
    customer = models.BooleanField(blank=True, default=False)
    employee = models.BooleanField(blank=True, default=False)
    other = models.BooleanField(blank=True, default=False)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.counterparty

    class Meta:
        ordering = ["counterparty"]
        verbose_name = "Counterparty"
        verbose_name_plural = "Counterparties"


class InitialDebts(models.Model):
    """
    Basic information about the initial debts of counterparty:
    counterparty name, organization - counterparty, currency of debt, type of debt,
    amount of debt by debit or credit, general comments.
    """

    TypeDebts = (
        ("", ""),
        ("Lender", "Lender"),
        ("Borrower", "Borrower"),
        ("Other", "Other"),
    )

    counterparty = models.ForeignKey(Counterparties, on_delete=models.PROTECT, blank=False)
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, blank=False)
    debit = models.DecimalField(max_digits=15, decimal_places=2, default=0.0, blank=True, null=True)
    credit = models.DecimalField(max_digits=15, decimal_places=2, default=0.0, blank=True, null=True)
    comments = models.CharField(max_length=250, blank=True, null=True)
    currency = models.ForeignKey("Currencies", on_delete=models.PROTECT, blank=False)
    type_debt = models.CharField(max_length=10, choices=TypeDebts, blank=False)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return f"{self.counterparty}, {self.organization}, {self.type_debt}, DR: {self.debit}, CR: {self.credit}, {self.currency}"

    class Meta:
        ordering = ["counterparty", "organization"]
        verbose_name = "Counterparty initial debts"
        verbose_name_plural = "Counterparties initial debts"


class Currencies(models.Model):
    """Basic information about the currency of accounting: name and official currency code."""

    currency = models.CharField(max_length=10, unique=True)
    code = models.CharField(max_length=3, blank=False)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.code

    class Meta:
        ordering = ["currency"]
        verbose_name = "Currency"
        verbose_name_plural = "Currencies"


class Items(models.Model):
    """
    Directory of cash inflows and outflows. Each item has attributes:
    name: customers item name,
    code: the system item name, which is not available for the user to change,
    group: economic item group,
    flow: direction of cash flow by item on document (Receipts/Payments),
    activity: type of economic activity by item (operating/financial/investment)

    Some items are of a systemic nature and cannot be deleted by users.
    Lists of types of economic activities and groups of articles are permanent,
    unchangeable, and are not available to the user for modification or deletion.
    """

    FLOW_DIRECTION = (
        (RECEIPTS, RECEIPTS),
        (PAYMENTS, PAYMENTS),
    )
    ITEM_GROUPS = (
        (SALES_INCOME, SALES_INCOME),
        (DIRECT_EXPENSES, DIRECT_EXPENSES),
        (ADMIN_EXPENSES, ADMIN_EXPENSES),
        (COMMERCIAL_EXPENSES, COMMERCIAL_EXPENSES),
        (PRODUCTION_COSTS, PRODUCTION_COSTS),
        (OTHER, OTHER),
        (LOANS, LOANS),
        (FIXED_ASSETS, FIXED_ASSETS),
        (PROJECTS, PROJECTS),
    )

    ACTIVITIES = (
        (OPERATING, OPERATING),
        (FINANCING, FINANCING),
        (INVESTING, INVESTING),
    )

    GROUP_ACTIVITIES = {
        ITEM_GROUPS[0][0]: OPERATING,
        ITEM_GROUPS[1][0]: OPERATING,
        ITEM_GROUPS[2][0]: OPERATING,
        ITEM_GROUPS[3][0]: OPERATING,
        ITEM_GROUPS[4][0]: OPERATING,
        ITEM_GROUPS[5][0]: OPERATING,
        ITEM_GROUPS[6][0]: FINANCING,
        ITEM_GROUPS[7][0]: INVESTING,
        ITEM_GROUPS[8][0]: INVESTING,
    }

    @classmethod
    def get_activity(cls, group):
        activities = {
            1: [cls.ITEM_GROUPS[0:5]],
            2: [cls.ITEM_GROUPS[6]],
            3: [cls.ITEM_GROUPS[7:8]],
        }
        return [k for k in activities if set(activities[k]) & {group}]

    name = models.CharField(max_length=100, unique=True, blank=True, null=True)
    code = models.CharField(max_length=100, unique=True, blank=True, null=True)
    group = models.CharField(max_length=100, choices=ITEM_GROUPS, blank=False)
    flow = models.CharField(max_length=100, choices=FLOW_DIRECTION, blank=True)
    activity = models.CharField(max_length=100, choices=ACTIVITIES, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["group", "name"]
        verbose_name = "Item"
        verbose_name_plural = "Items"

    def get_absolute_url(self):
        return "/items"

    @classmethod
    def populate(cls):
        admins = User.objects.filter(is_superuser=True).order_by("id")
        if not admins:
            return

        admin = admins[0]
        for item in ITEMS:
            if cls.objects.filter(code=item["code"]).count() > 0:
                continue
            obj = cls(**item)
            obj.user = admin
            obj.save()


class CurrenciesRates(models.Model):
    """
    Register for storing information about exchange rates.
    Each entry has information about the date, currency pair and official exchange rate.
    """

    date = models.DateField(blank=False)
    accounting_currency = models.ForeignKey(
        Currencies,
        related_name="cur1",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    currency = models.ForeignKey(
        Currencies,
        on_delete=models.CASCADE,
        related_name="cur2",
        blank=True,
        null=True,
    )
    rate = models.DecimalField(max_digits=15, decimal_places=6, blank=False, default=0.00)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return f"{self.accounting_currency}, {self.currency}, {self.date}, {self.rate}"

    class Meta:
        ordering = ["date", "accounting_currency", "currency"]
        verbose_name = "Rate"
        verbose_name_plural = "Currency rates"

directory/templates/directory/counterparties.html
{% extends 'registers/base.html' %}
{% block title %}Counterparties{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'registers/css/style.css' %}">

<div class="container">
    <div class="row d-grid gap-2 d-md-flex justify-content-md-end">
        <div class="col-md-12"></div>
        <div class="col-md-10">
            <H1>Counterparties</H1>
        </div>
        <div class="col-md-2">
            <a href="{% url 'counterparty_add' %}" class="btn btn-info" name="btn_add">ADD NEW</a>
        </div>
    </div>
    <br>
    <div class="row p-1 g-1">
        <div class="table-responsive" style="height: 500px">
            <table class="table table-condensed table-scroll table-striped ">
                <tr>
                    <th align="center">Counterparty</th>
                    <th align="center">Supplier</th>
                    <th align="center">Customer</th>
                    <th align="center">Employee</th>
                    <th align="center">Other</th>
                    <th align="center">Comments</th>
                    <th align="center"></th>
                </tr>
                {% for i in counterparties %}
                <tr>
                    <td width="100">{{i.counterparty}}</td>
                    <td width="10" align="center">{% if i.suppliers %}<i class="bi bi-check2-square"></i>{% endif %}
                    </td>
                    <td width="10" align="center">{% if i.customer %}<i class="bi bi-check2-square"></i>{% endif %}</td>
                    <td width="10" align="center">{% if i.employee %}<i class="bi bi-check2-square"></i>{% endif %}</td>
                    <td width="10" align="center">{% if i.other %}<i class="bi bi-check2-square"></i>{% endif %}</td>
                    <td width="100">{% if i.comments is not None %}{{i.comments}}{% endif %}</td>
                    <td width="80" align="center">
                        <a href="{% url 'counterparty_id' i.id %}" class='btn btn-info btn-xs' data-bs-toggle="tooltip"
                           data-bs-placement="top" title="edit"><i class="bi bi-pencil-square"></i></a>
                        <a href="{% url 'counterparty_del' i.id %}" class='btn btn-info btn-xs' data-bs-toggle="tooltip"
                           data-bs-placement="top" title="delete"><i class="bi bi-trash3"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

directory/templates/directory/expenses_item_id.html
{% extends 'registers/base.html' %}
{% block title %}Expenses items{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4 border p-2 shadow">
            <form  method='POST'>
                <div class="row p-2 g-3">
                    <div class="col-md-10">
                        <h2>Add new expense item</h2>
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="col-md-12">
                            <button class="btn btn-info" type="submit" name="btn_add">SAVE</button>
                            <a href="/expenses_items" class='btn btn-info'>CANCEL</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

directory/templates/directory/income_item_id.html
{% extends 'registers/base.html' %}
{% block title %}Income items{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4 border p-2 shadow">
            <form  method='POST'>
                <div class="row p-2 g-3">
                    <div class="col-md-10">
                        <h2>Add new income item</h2>
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="col-md-12">
                            <button class="btn btn-info" type="submit" name="btn_add">SAVE</button>
                            <a href="/income_items" class='btn btn-info'>CANCEL</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

directory/templates/directory/income_items.html
{% extends 'registers/base.html' %}
{% block title %}Income items{% endblock %}
{% load crispy_forms_tags %}
{% block content %}



<div class="container">
    <div class="row d-grid gap-2 d-md-flex justify-content-md-end">
        <div class="col-md-12"></div>
        <div class="col-md-10">
            <H1>Income items</H1>
        </div>
        <div class="col-md-2">
            <a href="{% url 'income_item_add' %}" class="btn btn-info" name="btn_add">ADD NEW</a>
        </div>
    </div>
    <br>
        <div class="row p-1 g-1">
            <div class="table-responsive" style="height: 550px">
                <table class="table table-condensed table-scroll table-striped" >
                    <tr>
                        <th align="center">Income items</th>
                        <th align="center">Income groups</th>
                        <th align="center"></th>
                    </tr>
                    {% for i in income_items %}
                    <tr>
                        <td width="300">{% if not i.code is None %}{{ i.name | add:" *" }}{% else %}{{ i.name }}{% endif %}</td>
                        <td width="300">{{i.get_group_display}}</td>
                        <td width="10" align="center">
                            <a href="{% url 'income_item_id' i.id %}" class='btn btn-info btn-xs' data-bs-toggle="tooltip"
               data-bs-placement="top" title="edit"><i class="bi bi-pencil-square"></i></a>
                            <a href="{% url 'item_del' i.id %}" class='btn btn-info btn-xs' data-bs-toggle="tooltip"
               data-bs-placement="top" title="edit"><i class="bi bi-trash3"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
{% endblock %}

directory/templates/directory/initial_debt_delete.html
{% extends 'registers/base.html' %}
{% block title %}Delete initial debt{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row h-100 p-2 g-3 justify-content-center" >
        <div class="col-md-8 border p-3 shadow">
             <form method="post">
                 {% csrf_token %}
                 {% if error %}
                    {{ error }}
                    {% else %}
                 <h3>Are you sure you want to delete</h3>
                 <h4>initial debt: "{{ object }}"</h4>
                 <br>
                 <div class="row">
                    <div class="col-md-2">
                        <button class="btn btn-info" type="submit" name="btn_del">DELETE</button>
                    </div>
                    <div class="col-md-2">
                        <a href="/initial_debts" class='btn btn-info'>CANCEL</a>
                    </div>
                    {% endif %}
                 </div>
             </form>
        </div>
    </div>
</div>
{% endblock %}

directory/templates/directory/initial_debts.html
{% extends 'registers/base.html' %}
{% block title %}Initial debts{% endblock %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}


<div class="container-fluid px-10">
    <div class="row">
        <div class="col-md-1 border p-2 shadow"></div>
        <form action="" method="GET"
            hx-get="/initial_debts/list"
            hx-trigger="change"
            hx-target="#id_table">
        <div class="col-md-2 border p-2 shadow">
            <br><br>
            <br><br>
            <h4>FILTER</h4>
            {% csrf_token %}
            <div class="form-group">
            {{ form.organization.label_tag }}
            {% render_field form.organization class="select form-control" %}
            </div>
            <div class="form-group">
                {{ form.counterparty.label_tag }}
                {% render_field form.counterparty class="select form-control" %}
            </div>
            <div class="form-group">
            {{ form.type_debt.label_tag }}
            {% render_field form.type_debt class="select form-control" %}
            </div>
            <div hx-get="/initial_debts/list" hx-trigger="click" hx-target="#id_table">
                <button class="btn btn-info" type="reset" name="btn_reset" >RESET FILTERS</button>
            </div>
        </div>
            <div class="col-md-8 border p-2 shadow">
                <div class="row d-grid gap-2 d-md-flex justify-content-md-end">
                    <div class="col-md-10 fw-bold"><H2>Counterparties initial debts</H2></div>
                    <div class="col-md-1">
                        <a href="{% url 'initial_debt_add' %}" class="btn btn-info" name="btn_add">ADD NEW DEBT</a>
                    </div>
                </div>
                <br>
                <div class="table-responsive" style="height: 550px">
                    {% include "directory/initial_debts_list.html" %}
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

directory/templates/directory/initial_debts_list.html
<table class="table table-condensed table-scroll table-striped" >
    <tr>
        <th align="center">Organization</th>
        <th align="center">Counterparty</th>
        <th align="center">Type of debt</th>
        <th align="center">Initial debit</th>
        <th align="center">Initial credit</th>
        <th align="center">Currency</th>
        <th align="center">Comments</th>
        <th align="center"></th>
    </tr>
    {% for i in object_list %}
    <tr>
        <td width="100">{{i.organization}}</td>
        <td width="100">{{ i.counterparty }}</td>
        <td width="100">{{ i.type_debt }}</td>
        <td width="50" align="right">{% if i.debit is not None %}{{ i.debit }}{% endif %}</td>
        <td width="50" align="right">{% if i.credit is not None %}{{ i.credit }}{% endif %}</td>
        <td width="50">{{ i.currency }}</td>
        <td width="100">{% if i.comments is not None %}{{i.comments}}{% endif %}</td>
        <td width="80" align="center">
            <a href="{% url 'initial_debt_id' i.id %}" class='btn btn-info btn-xs' data-bs-toggle="tooltip"
                            data-bs-placement="top" title="edit"><i class="bi bi-pencil-square"></i></a>
            <a href="{% url 'initial_debt_del' i.id %}" class='btn btn-info btn-xs' data-bs-toggle="tooltip"
                            data-bs-placement="top" title="delete"><i class="bi bi-trash3"></i></a>
        </td>
    </tr>
    {% endfor %}
</table>

directory/templates/directory/item_id.html
{% extends 'registers/base.html' %}
{% block title %}Item{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4 border p-2 shadow">
            <form  method='POST'>
                <div class="row p-2 g-3">
                    <div class="col-md-10">
                        <h2>Add new item</h2>
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="col-md-12">
                            <button class="btn btn-info" type="submit" name="btn_add">SAVE</button>
                            <a href="/items" class='btn btn-info'>CANCEL</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

directory/templates/directory/items_list.html
<table class="table table-condensed table-scroll table-striped" id="id_table" >
    <tr>
        <th align="center">code</th>
        <th align="center">name</th>
        <th align="center">group</th>
        <th align="center">flow</th>
        <th align="center">activity</th>
        <th align="center"></th>
    </tr>
    {% for i in object_list %}
    <tr>
        <td width="200">{% if not i.code is None %}{{i.code}}{% endif %}</td>
        <td width="200">{% if not i.code is None %}{{ i.name | add:" *" }}{% else %}{{ i.name }}{% endif %}</td>
        <td width="150">{{ i.get_group_display }}</td>
        <td width="150">{{ i.get_flow_display }}</td>
        <td width="150">{% if not i.activity is None %}{{i.get_activity_display}}{% endif %}</td>
        <td width="10" align="center" style='white-space: nowrap'>
            <a href="{% url 'item_id' i.id %}" class='btn btn-info btn-xs' data-bs-toggle="tooltip"
               data-bs-placement="top" title="edit"><i class="bi bi-pencil-square"></i></a>
            <a href="{% url 'item_del' i.id %}" class='btn btn-info btn-xs' data-bs-toggle="tooltip"
               data-bs-placement="top" title="delete"><i class="bi bi-trash3"></i></a>
         </td>
    </tr>
    {% endfor %}
</table>

directory/templates/directory/organization_add.html
{% extends 'registers/base.html' %}
{% block title %}Organization{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4 border p-2 shadow">
            <form  method='POST'>
                <div class="col-md-10">
                    <h2>Add new organization</h2>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="col-md-12">
                        <button class="btn btn-info" type="submit" name="btn_add">SAVE</button>
                        <a href="/organizations" class='btn btn-info'>CANCEL</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

directory/templates/directory/organizations.html
{% extends 'registers/base.html' %}
{% block title %} Organizations {% endblock %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'registers/css/style.css' %}">

<div class="container">
    <div class="row d-grid gap-2 d-md-flex justify-content-md-end text-center">
        <div class="col-md-12"></div>
        <div class="col-md-7">
            <H1>Organizations</H1>
        </div>
        <div class="col-md-4">
            <a href="{% url 'organization_add' %}" class="btn btn-info" name="btn_add">ADD NEW</a>
        </div>
    </div>
    <br>
    <div class="row p-1 g-1">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="table-responsive" style="height: 500px">
                <table class="table table-condensed table-scroll table-striped">
                    <tr>
                        <th align="center">Organizations</th>
                        <th align="center">Comments</th>
                        <th align="center"></th>
                    </tr>
                    {% for i in organizations %}
                    <tr>
                        <td width="400">{{i.organization}}</td>
                        <td width="400">{% if not i.comments is None %}{{i.comments}}{% endif %}</td>
                        <td width="100" align="center">
                            <a href="{% url 'organization_id' i.id %}" class='btn btn-info btn-xs'
                               data-bs-toggle="tooltip"
                               data-bs-placement="top" title="edit"><i class="bi bi-pencil-square"></i></a>
                            <a href="{% url 'organization_del' i.id %}" class='btn btn-info btn-xs'
                               data-bs-toggle="tooltip"
                               data-bs-placement="top" title="delete"><i class="bi bi-trash3"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}