finance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("", include("directory.urls")),
    path("", include("payments.urls")),
    path("", include("planning.urls")),
    path("", include("registers.urls")),
    path("", include("users.urls")),
    path("", include("tools.urls")),
]

planning/urls.py
from django.urls import path

from planning.views import (
    PaymentsPlanView,
    PaymentsPlanIdView,
    PaymentsPlanDeleteView,
    PaymentsPlanUploadFileView,
    ReceiptsPlanView,
    ReceiptsPlanIdView,
    ReceiptsPlanDeleteView,
    ReceiptsPlanUploadFileView,
    CalculationView,
    CalculationIdView,
    CalculationPlanDeleteView,
)

urlpatterns = [
    path("payments_plan/", PaymentsPlanView.as_view(), name="payments_plan"),
    path(
        "payments_plan/list",
        PaymentsPlanView.htmx_list,
        name="payments_plan_list",
    ),
    path(
        "payments_plan/<int:pk>",
        PaymentsPlanIdView.as_view(),
        name="payments_plan_id",
    ),
    path(
        "payments_plan/add/",
        PaymentsPlanIdView.as_view(),
        name="payments_plan_add",
    ),
    path(
        "payments_plan/copy/<int:from_pk>",
        PaymentsPlanIdView.as_view(),
        name="payments_plan_copy",
    ),
    path(
        "payments_plan/to_fact/<int:pk_fact>",
        PaymentsPlanIdView.as_view(),
        name="payments_plan_to_fact",
    ),
    path(
        "<int:pk>/payments_plan_delete",
        PaymentsPlanDeleteView.as_view(),
        name="payments_plan_delete",
    ),
    path(
        "payments_plan/upload_file",
        PaymentsPlanUploadFileView.as_view(),
        name="payments_plan_upload_file",
    ),
    path(
        "payments_plan/projects",
        PaymentsPlanIdView.htmx_projects,
        name="payments_plan_projects",
    ),
    path("calculations/", CalculationView.as_view(), name="calculations"),
    path(
        "calculations/list",
        CalculationView.htmx_list,
        name="calculations_list",
    ),
    path(
        "calculations/projects",
        CalculationIdView.htmx_projects,
        name="calculations_projects",
    ),
    path(
        "calculation/delete_plan/<int:pk>",
        CalculationPlanDeleteView.as_view(),
        name="calculation_delete_plan",
    ),
    path(
        "calculation/<int:pk>/list",
        CalculationIdView.htmx_list,
        name="calculations_id_list",
    ),
    path(
        "calculation/<int:calc_pk>/create_plan",
        CalculationIdView.as_view(),
        name="calculation_create_plan",
    ),
    path(
        "calculation/<int:pk>",
        CalculationIdView.as_view(),
        name="calculation_id",
    ),
    path("calculation/add", CalculationIdView.as_view(), name="calculation_add"),
    path(
        "calculation/copy/<int:from_pk>",
        CalculationIdView.as_view(),
        name="calculation_copy",
    ),
    path("receipts_plan/", ReceiptsPlanView.as_view(), name="receipts_plan"),
    path(
        "receipts_plan/<int:pk>",
        ReceiptsPlanIdView.as_view(),
        name="receipts_plan_id",
    ),
    path(
        "receipts_plan/add/",
        ReceiptsPlanIdView.as_view(),
        name="receipts_plan_add",
    ),
    path(
        "receipts_plan/copy/<int:from_pk>",
        ReceiptsPlanIdView.as_view(),
        name="receipts_plan_copy",
    ),
    path(
        "<int:pk>/receipts_plan_delete",
        ReceiptsPlanDeleteView.as_view(),
        name="receipts_plan_delete",
    ),
    path(
        "receipts_plan/projects",
        ReceiptsPlanIdView.htmx_projects,
        name="receipts_plan_projects",
    ),
    path(
        "receipts_plan/list",
        ReceiptsPlanView.htmx_list,
        name="receipts_plan_list",
    ),
    path(
        "receipts_plan/receipts_plan_upload_file",
        ReceiptsPlanUploadFileView.as_view(),
        name="receipts_plan_upload_file",
    ),
]

tools/urls.py
urlpatterns = [
    # path("s3cr3t/rel04d/", DataLoadView.as_view(), name="dataload"),
]

payments/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin

from directory.constants import RECEIPTS, PAYMENTS
from directory.models import (
    Organization,
    PaymentAccount,
    Currencies,
    Project,
    Counterparties,
    Items,
)


from planning.models import PaymentDocumentPlan


class PaymentDocuments(LoginRequiredMixin, models.Model):
    FlowDirection = (
        ("Receipts", RECEIPTS),
        ("Payments", PAYMENTS),
    )
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    flow = models.CharField(max_length=10, choices=FlowDirection, blank=True)
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, blank=False)
    date = models.DateField(blank=False)
    inflow_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0, blank=False)
    outflow_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0, blank=False)
    account = models.ForeignKey(PaymentAccount, on_delete=models.PROTECT, blank=False)
    currency = models.ForeignKey(Currencies, on_delete=models.PROTECT, blank=True, null=True)
    project = models.ForeignKey(Project, on_delete=models.PROTECT, blank=True, null=True)
    counterparty = models.ForeignKey(Counterparties, on_delete=models.PROTECT, blank=False)
    by_plan = models.ForeignKey(PaymentDocumentPlan, on_delete=models.PROTECT, blank=True, null=True)
    item = models.ForeignKey(Items, on_delete=models.PROTECT, blank=False)
    comments = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        if self.flow == "Receipts":
            amount = self.inflow_amount
        else:
            amount = self.outflow_amount
        return f"{self.date}, {self.counterparty}, {self.item}, {amount}, {self.currency}, {self.flow}"

    class Meta:
        ordering = ["flow", "organization", "date", "item"]
        verbose_name = "Payment document"
        verbose_name_plural = "Payment documents"

    @classmethod
    def from_plan(cls, plan_id):
        obj = PaymentDocumentPlan.objects.get(pk=plan_id)
        return cls(
            organization=obj.organization,
            date=obj.date,
            outflow_amount=obj.outflow_amount,
            inflow_amount=obj.inflow_amount,
            currency=obj.currency,
            project=obj.project,
            counterparty=obj.counterparty,
            by_plan=obj,
            item=obj.item,
            flow=obj.flow,
            comments=obj.comments,
        )

planning/models.py
from django.db import models
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

from directory.constants import R_OF_ISSUED_LOAN
from directory.data import R_LOANS_INTEREST, P_OF_RECEIVED_LOAN, P_LOANS_INTEREST

from directory.models import (
    Organization,
    Counterparties,
    Project,
    Currencies,
    Items,
)


class Calculations(LoginRequiredMixin, models.Model):
    FlowDirection = (
        ("Receipts", "Receipts"),
        ("Payments", "Payments"),
    )

    TypeCalculation = (
        ("constant", "Constant payments"),
        ("annuity", "Credit: annuity"),
        ("differential", "Credit: differentiated"),
    )

    Frequency = (
        ("annually", "annually"),
        ("monthly", "monthly"),
        ("weekly", "weekly"),
        ("daily", "daily"),
    )

    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    type_calc = models.CharField(max_length=200, choices=TypeCalculation, blank=True)
    flow = models.CharField(max_length=10, choices=FlowDirection, blank=True)
    name = models.CharField(max_length=100, blank=True, unique=True)
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, blank=True)
    counterparty = models.ForeignKey(Counterparties, on_delete=models.PROTECT, blank=True)
    project = models.ForeignKey(Project, on_delete=models.PROTECT, blank=True, null=True)
    is_cash = models.BooleanField(blank=True, default=False)
    currency = models.ForeignKey(Currencies, on_delete=models.PROTECT, blank=True)
    comments = models.CharField(max_length=250, blank=True, null=True)
    item = models.ForeignKey(Items, on_delete=models.PROTECT, blank=True)
    date_first = models.DateField(blank=True)
    amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True)
    term = models.IntegerField(blank=True, null=True)
    frequency = models.CharField(
        max_length=200,
        choices=Frequency,
        blank=True,
        default="monthly",
        null=True,
    )
    loan_rate = models.DecimalField(max_digits=15, decimal_places=2, default=0.00, blank=True, null=True)

    def __str__(self):
        return self.name

    @staticmethod
    def get_series_constant(date_first, frequency, term, amount, item):
        frequency_days = {
            "annually": 365,
            "monthly": 31,
            "weekly": 7,
            "daily": 1,
        }
        days = frequency_days.get(frequency)
        date_pay = date_first
        number = date_first.day
        data_list = [(date_pay, amount, item)]
        for i in range(term):
            if frequency in ["weekly", "daily"]:
                date_pay = date_pay + datetime.timedelta(days=days)
            else:
                date_pay = (date_pay + datetime.timedelta(days=days)).replace(day=number)
            data_list.append((date_pay, amount, item))
        return data_list

    @staticmethod
    def get_series_differ(date_first, term, loan_rate, amount, item_debt, item_per):
        date_pay = date_first
        number = date_first.day
        debt_pay = amount / term
        balance_owed = amount
        data_list = [
            (date_pay, debt_pay, item_debt),
            (date_pay, amount * loan_rate / 1200, item_per),
        ]

        for i in range(term - 1):
            date_pay = (date_pay + datetime.timedelta(days=31)).replace(day=number)
            balance_owed -= debt_pay
            per_pay = balance_owed * loan_rate / 1200
            data_list.append((date_pay, debt_pay, item_debt))
            data_list.append((date_pay, per_pay, item_per))

        return data_list

    @staticmethod
    def get_series_annuity(date_first, term, loan_rate, amount, item_debt, item_per):
        date_pay = date_first
        number = date_first.day
        annuity = (amount * loan_rate / 1200) / (1 - (1 + loan_rate / 1200) ** (-term))
        balance_owed = amount
        data_list = []

        for i in range(term):
            date_pay = (date_pay + datetime.timedelta(days=31)).replace(day=number)
            per_pay = balance_owed * loan_rate / 1200
            debt_pay = annuity - per_pay
            balance_owed -= debt_pay
            data_list.append((date_pay, debt_pay, item_debt))
            data_list.append((date_pay, per_pay, item_per))

        return data_list

    def create_plan_payments(self):
        existing_plan = PaymentDocumentPlan.objects.filter(calculation=self).order_by("date").all()

        if self.flow == "Payments":
            item_per = Items.objects.get(code=P_LOANS_INTEREST)
            item_debt = Items.objects.get(code=P_OF_RECEIVED_LOAN)
        else:
            item_per = Items.objects.get(code=R_LOANS_INTEREST)
            item_debt = Items.objects.get(code=R_OF_ISSUED_LOAN)

        if self.type_calc == "constant":
            data_list = self.get_series_constant(
                self.date_first,
                self.frequency,
                self.term,
                self.amount,
                self.item,
            )
        elif self.type_calc == "differential":
            data_list = self.get_series_differ(
                self.date_first,
                self.term,
                self.loan_rate,
                self.amount,
                item_debt,
                item_per,
            )
        else:
            data_list = self.get_series_annuity(
                self.date_first,
                self.term,
                self.loan_rate,
                self.amount,
                item_debt,
                item_per,
            )

        for i, data in enumerate(data_list):
            plan = PaymentDocumentPlan(
                calculation=self,
                user=self.user,
                organization=self.organization,
                currency=self.currency,
                is_cash=self.is_cash,
                project=self.project,
                counterparty=self.counterparty,
                comments=self.comments,
                flow=self.flow,
                date=data[0],
            )
            if self.flow == "Payments":
                plan.outflow_amount = data[1]
                plan.inflow_amount = 0
                plan.item = data[2]
            else:
                plan.outflow_amount = 0
                plan.inflow_amount = data[1]
                plan.item = data[2]

            if len(existing_plan) > i:
                plan.id = existing_plan[i].id
            plan.save()

        PaymentDocumentPlan.objects.filter(calculation=self, date__gt=data_list[-1][0]).delete()

    def get_absolute_url(self):
        return "/calculations"


class PaymentDocumentPlan(LoginRequiredMixin, models.Model):
    FlowDirection = (
        ("Receipts", "Receipts"),
        ("Payments", "Payments"),
    )
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True)
    flow = models.CharField(max_length=10, choices=FlowDirection, blank=True)
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, blank=True, null=True)
    date = models.DateField(blank=True)
    inflow_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    outflow_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    currency = models.ForeignKey(Currencies, on_delete=models.PROTECT, blank=True)
    is_cash = models.BooleanField(blank=False, default=False)
    project = models.ForeignKey(Project, on_delete=models.PROTECT, blank=False, null=True)
    counterparty = models.ForeignKey(Counterparties, on_delete=models.PROTECT, blank=True)
    item = models.ForeignKey(Items, on_delete=models.PROTECT, blank=True)
    calculation = models.ForeignKey(Calculations, on_delete=models.CASCADE, blank=True, null=True)
    comments = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.pk}"

    class Meta:
        ordering = ["organization", "date", "item"]
        verbose_name = "Payment-plan document"
        verbose_name_plural = "Payment-plan documents"

planning/templates/planning/calculation_id.html
{% extends 'registers/base.html' %}
{% block title %}New calculation{% endblock %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}

<div class="container-fluid px-10">
    <form  method='POST'>
        {% csrf_token %}
        <div class="row text-center">
            <div class="col-md-4 border p-2 shadow"><h1>New calculation</h1></div>
            <div class="col-md-8 border p-2 shadow"><H3>List of payment documents</H3></div>
        </div>
        <div class="row">
            <div class="col-md-2 border p-2 shadow">
                <div class="form-group">
                    {{ form.name|as_crispy_field }}
                    {{ form.flow|as_crispy_field }}
                    {% if  form.type_calc == '' %}
                        {{ form.name.as_hidden }}
                    {% endif %}
                </div>
                <div id="div_id_organization"
                     class="form-group"
                     hx-get="/calculations/projects"
                     hx-vals="js:{organization:document.getElementById('id_organization').value}"
                     hx-trigger="change"
                     hx-target="#id_project">
                {% render_field form.organization class="select form-control" hx-get="/calculations/projects" hx-trigger="change" hx-target="#id_account" %}
                </div>
                <div class="form-group">{% render_field form.counterparty class="select form-control" %}</div>
                <div class="form-group">{% render_field form.project class="select form-control" %}</div>
                <div class="form-group">{% render_field form.item class="select form-control" %}</div>
                <div class="form-group">{% render_field form.comments class="select form-control" %}</div>
            </div>
            <div class="col-md-2">
                    {{ form.type_calc|as_crispy_field }}
                    {{ form.loan_rate|as_crispy_field }}
                    {{ form.amount|as_crispy_field }}
                <div class="row text-left">
                    <div class="col-md-8 form-group">{% render_field form.currency class="select form-control" %}</div>
                    <div class="col-md-4 form-group">{{ form.is_cash|as_crispy_field }}</div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">{{ form.term|as_crispy_field }}</div>
                    <div class="col-md-6 form-group">{{ form.frequency|as_crispy_field }}</div>
                </div>
                    {{ form.date_first|as_crispy_field }}
                </div>
            <div class="col-md-8">
                <div class="table-responsive" style="height: 450px">
                    {% include "planning/calc_to_plan_list.html" %}
                </div>
            </div>
        </div>
            <div class="row text-center">
                <div class="col-md-4">
<!--                    <button class="btn btn-warning" type="submit" name="btn_save">SAVE</button>-->
                    <button class="btn btn-warning" type="submit" name="btn_create">SAVE AND CREATE PLAN</button>
                    {% if object.id %}
                    <a href="{% url 'calculation_delete_plan' object.id %}" class='btn btn-warning'>DELETE ALL</a>
                    {% endif %}
                    <input action="action" onclick="window.history.go(-1); return false;"
       					class='btn btn-warning' type="submit" value="CANCEL"/>

<!--                    <a href="/calculations" class='btn btn-warning'>CANCEL</a>-->
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

planning/templates/planning/payments_plan.html
{% extends 'registers/base.html' %}
{% block title %}Payments plan{% endblock %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}

<div class="container-fluid px-10">
    <div class="row">
        <form action="" method="GET"
            hx-get="/payments_plan/list"
            hx-trigger="change"
            hx-target="#id_table">
        <div class="col-md-2 border p-2 shadow">
                <h4>FILTER</h4>
                {% csrf_token %}
                <div class="form-group">
                {{ form.ordering.label_tag }}
                {% render_field form.ordering class="select form-control" %}
                </div>
                <div class="form-group">
                {{ form.date.label_tag }}
                {% render_field form.date class="select form-control" %}
                </div>
                <div class="form-group">
                {{ form.date_end.label_tag }}
                {% render_field form.date_end class="select form-control" %}
                </div>
                <div id="div_id_organization"
                     class="form-group"
                     hx-get="/payments_plan/projects"
                     hx-vals="js:{organization:document.getElementById('id_organization').value}"
                     hx-trigger="change"
                     hx-target="#id_project">
                {% render_field form.organization class="select form-control" hx-get="/payments_plan/project" hx-trigger="change" hx-target="#id_account" %}
                </div>
                <div class="form-group">
                {% render_field form.project class="select form-control" %}
                </div>
                <div class="form-group">
                {% render_field form.item class="select form-control" %}
                </div>
                <div class="form-group">
                {% render_field form.counterparty class="select form-control" %}
                </div>
                <div class="form-group">
                {% render_field form.calculation class="select form-control" %}
                </div>
                <div class="row text-left">
                    <div class="col-md-8 form-group">{% render_field form.currency class="select form-control" %}</div>
                    <div class="col-md-4 form-group">{{ form.is_cash|as_crispy_field }}</div>
                </div>
                <div hx-get="/payments_plan/list" hx-trigger="click" hx-target="#id_table">
                    <button class="btn btn-warning" type="reset" name="btn_reset" >RESET FILTERS</button>
                </div>
        </div>
        <div class="col-md-10 border p-2 shadow">
            <div class="row d-grid gap-2 d-md-flex justify-content-md-end">
                <div class="col-md-4 fw-bold"><h2>Payment requests</h2></div>
                <div class="col-md-8">
                    <a href="{% url 'payments_plan_add' %}" class="btn btn-warning" name="btn_add">ADD NEW REQUEST</a>
                    <a href="{% url 'calculation_add' %}" class="btn btn-warning" name="btn_add">ADD NEW SERIES WITH CALCULATION</a>
                    <a href="{% url 'payments_plan_upload_file' %}" class="btn btn-warning" name="btn_add">IMPORT FROM FILE</a>
                    <button  class="btn btn-warning" name="btn_to_file">SAVE TO FILE</button>
                </div>
            </div>
            <br>
            <div class="table-responsive" style="height: 550px">
                {% include "planning/payments_plan_list.html" %}
            </div>
        </div>
        </form>
    </div>
</div>

{% endblock %}

planning/templates/planning/payments_plan_id.html
{% extends 'registers/base.html' %}
{% block title %}Payment plan{% endblock %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}

<div class="container">
    <form  method='POST'>
        {% csrf_token %}
        <div class="row text-center">
            <div class="col-md-4 border p-2 shadow"></div>
            <div class="col-md-4 border p-2 shadow">
                <h1>Payment request</h1>
                <div id="div_id_organization"
                     class="form-group"
                     hx-get="/payments_plan/projects"
                     hx-vals="js:{organization:document.getElementById('id_organization').value}"
                     hx-trigger="change"
                     hx-target="#id_project">
                {% render_field form.organization class="select form-control" hx-get="/payments_plan/project" hx-trigger="change" hx-target="#id_account" %}
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">{{ form.date|as_crispy_field }}</div>
                    <div class="col-md-6 form-group">{{ form.outflow_amount|as_crispy_field }}</div>
                </div>
                <div class="row text-left">
                    <div class="col-md-8 form-group">{% render_field form.currency class="select form-control" %}</div>
                    <div class="col-md-4 form-group">{{ form.is_cash|as_crispy_field }}</div>
                </div>
                <div class="form-group">
                    {% render_field form.counterparty class="select form-control" %}
                </div>
                <div class="form-group">
                    {% render_field form.project class="select form-control" %}
                </div>
                <div class="form-group">
                    {% render_field form.item class="select form-control" %}
                </div>
                <div class="form-group">
                    {% render_field form.calculation class="select form-control" %}
                </div>
                <div  class="form-group">{% render_field form.comments class="select form-control" %}</div>
                <div class="row">
                    <br>
                    <div class="col-md-12">
                        <button class="btn btn-warning" type="submit" name="btn_save">SAVE</button>
                        <input action="action" onclick="window.history.go(-1); return false;"
                               class='btn btn-warning' type="submit" value="CANCEL"/>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

planning/templates/planning/payments_plan_upload_file.html
{% extends 'registers/base.html' %}
{% block title %}Payments plan upload{% endblock %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}

<div class="container">
    <form  method='POST' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-warning" type="submit" name="btn_upload">UPLOAD</button>
        <a href="/payments_plan" class='btn btn-warning'>CANCEL</a>
    </form>
</div>
{% endblock %}

planning/templates/planning/receipts_plan.html
{% extends 'registers/base.html' %}
{% block title %}Receipts plan{% endblock %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <form action="" method="GET"
            hx-get="/receipts_plan/list"
            hx-trigger="change"
            hx-target="#id_table">
        <div class="col-md-2 border p-2 shadow">
                <h4>FILTER</h4>
                {% csrf_token %}
                <div class="form-group">
                {{ form.ordering.label_tag }}
                {% render_field form.ordering class="select form-control" %}
                </div>
                <div class="form-group">
                {{ form.date.label_tag }}
                {% render_field form.date class="select form-control" %}
                </div>
                <div class="form-group">
                {{ form.date_end.label_tag }}
                {% render_field form.date_end class="select form-control" %}
                </div>
                <div id="div_id_organization"
                     class="form-group"
                     hx-get="/receipts_plan/projects"
                     hx-vals="js:{organization:document.getElementById('id_organization').value}"
                     hx-trigger="change"
                     hx-target="#id_project">
                {% render_field form.organization class="select form-control" hx-get="/receipts_plan/project" hx-trigger="change" hx-target="#id_account" %}
                </div>
                <div class="form-group">
                {% render_field form.project class="select form-control" %}
                </div>
                <div class="form-group">
                {% render_field form.item class="select form-control" %}
                </div>
                <div class="form-group">
                {% render_field form.counterparty class="select form-control" %}
                </div>
                <div class="form-group">
                {% render_field form.calculation class="select form-control" %}
                </div>
                <div class="row text-left">
                    <div class="col-md-8 form-group">{% render_field form.currency class="select form-control" %}</div>
                    <div class="col-md-4 form-group">{{ form.is_cash|as_crispy_field }}</div>
                </div>
                <div hx-get="/receipts_plan/list" hx-trigger="click" hx-target="#id_table">
                    <button class="btn btn-warning" type="reset" name="btn_reset" >RESET FILTERS</button>
                </div>
        </div>
        <div class="col-md-10">
            <div class="row">
                <div class="col-md-4 fw-bold"><h2>Planned receipts</h2></div>
                <div class="col-md-8">
                    <a href="{% url 'receipts_plan_add' %}" class="btn btn-warning" name="btn_add">ADD NEW PLAN</a>
                    <a href="{% url 'calculation_add' %}" class="btn btn-warning" name="btn_add">ADD NEW SERIES WITH CALCULATION</a>
                    <a href="{% url 'receipts_plan_upload_file' %}" class="btn btn-warning" name="btn_add">IMPORT FROM FILE</a>
                    <button  class="btn btn-warning" name="btn_to_file">SAVE TO FILE</button>
                </div>
            </div>
            <br>
            <div class="table-responsive" style="height: 550px">
                {% include "planning/receipts_plan_list.html" %}
            </div>
        </div>
        </form>
    </div>
</div>

{% endblock %}

planning/templates/planning/receipts_plan_id.html
{% extends 'registers/base.html' %}
{% block title %}Receipt plan{% endblock %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}

<div class="container">
    <form  method='POST'>
        {% csrf_token %}
        <div class="row text-center">
            <div class="col-md-4 border p-2 shadow"></div>
            <div class="col-md-4 border p-2 shadow">
                <h1>Planned receipt</h1>
                <div id="div_id_organization"
                     class="form-group"
                     hx-get="/receipts_plan/projects"
                     hx-vals="js:{organization:document.getElementById('id_organization').value}"
                     hx-trigger="change"
                     hx-target="#id_project">
                {% render_field form.organization class="select form-control" hx-get="/receipts_plan/project" hx-trigger="change" hx-target="#id_account" %}
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">{{ form.date|as_crispy_field }}</div>
                    <div class="col-md-6 form-group">{{ form.inflow_amount|as_crispy_field }}</div>
                </div>
                <div class="row text-left">
                    <div class="col-md-8 form-group">{% render_field form.currency class="select form-control" %}</div>
                    <div class="col-md-4 form-group">{{ form.is_cash|as_crispy_field }}</div>
                </div>
                <div class="form-group">
                    {% render_field form.counterparty class="select form-control" %}
                </div>
                <div class="form-group">
                    {% render_field form.project class="select form-control" %}
                </div>
                <div class="form-group">
                    {% render_field form.item class="select form-control" %}
                </div>
                <div  class="form-group">{% render_field form.comments class="select form-control" %}</div>
                <div class="row">
                    <br>
                    <div class="col-md-12">
                        <button class="btn btn-warning" type="submit" name="btn_save">SAVE</button>
                        <input action="action" onclick="window.history.go(-1); return false;"
                               class='btn btn-warning' type="submit" value="CANCEL"/>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}